title: Guido Schlabitz
show_downloads: true
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  nav_pages:
    - links.md
    - hacks/index.md
    - recipes/index.md
    - bio.md
  social_links:
    - title: GitHub
      url: "https://github.com/gschlabitz"
      icon: "fab fa-github"
    - title: LinkedIn
      url: "https://www.linkedin.com/in/guido-schlabitz/"
      icon: "fab fa-linkedin"
    - title: Twitter
      url: "https://twitter.com/gschlabitz"
      icon: "fab fa-twitter"
